CUMULUS-4780: Implemented partitioned schema for consolidated database (#4401)
* initial bootstrap schema files

* pdrs

* updated bootstrap files not partition

* update db-migration take use_bootstrap

* partitioning tables with cumulus_id

* changelog

* changelog

* security check

* archive old migration files add new

* add files to migrations dir

* lookup tables

* use global unique tables

* executions triggers

* fix executions trigger

* granules trigger,test-execution-model crossx insert

* files trigger

* rename

* update granule model

* trigger throw original error

* file model

* granules-executions-model test

* lib-execution

* isolate INSERT in savepoint

* lib/test-granule skip updateBatchGranulesCollection Duplicate granule_id move partition

* default executions partition

* db package unit tests pass except one skip

* handle granule collection_cumulus_id update in trigger

* triggers date precision duplidate granule_id additional foreign key fields in record

* update on cascade

* api unit tests passed

* ingest unit test

* use_bootstrap

* update iceberg schema

* test getExecution record instead of id

* adjust api test coverage

* api performance test

* move recent db migrations patches to migrations-archive

* file global uniqueness

* api test:coverge not meet

* timestamp precision 3

* table descriptions

* update index, db_partition_config terraform

* update variables order

* changelog

* remove accidental test.only

* add partition config to example fix USE_BOOTSTRAP env

* add const TIMESTAMP_PRECISION and getPartitionCount to lib

* Cannot find module lib

* use isCollisionError

* add unit test for db-migration lambda

* bootstrap vs standard migrations

* fix db-migration ci more unit tests

* update base model get take returningFields

* migrations to migrations-bootstrap

* update migrations-bootstrap directory seed and doc

* add granules_executions column description fix files_trigger function name

* update trigger use const names

* delete migrations-archive update model base type update execution upsert comment

* file collision on bucket key no collection_cumulus_id

* ts-check write-execution

* test granules files partition counts

* update integration arn required missing

* Fix generate_records scripts (#4420)

* add test to generate_records package.json

* add test:coverage to generate_records

* fix knex failed on attempted connection error: no pg_hba.conf entry for host

* generate_records unit test knex not connect remove env to README

* update postgres docker image to 17.4 update schema diagram ignore partition

* remove max partition limit use current year for execution partition base year

* increase fakeFileRecord bucketkey length

* remove base_year config, update granule file partition count

* revert fakeFileRecordFactory change

* should use fakeFileFactory in api/tests/endpoints/test-granules.js

* some tests set collection_cumulus_id later for fakeGranuleRecordFactory

* fix test fakeFileRecordFactory without required ids

* increase random string length reduce duplicate

* changed producerGranuleId to producergranuleId in test accidently

---------

Co-authored-by: Jonathan Kovarik <Jkovarik@users.noreply.github.com>