CUMULUS-2885: Update S3 code to AWS SDK v3 (#2909)
* fix memoizer logic

* update unit tests

* refactor

* fix bad merge

* update CHANGLEOG

* update Dynamo clients from v2 to v3

* fix bad merge

* update base Dynamo model code

* fix migration 2 code

* update GranulesFileCache for compat with v3 & update unit tests

* fix async operation and unit tests

* fix state file package

* fix dynamo client options for v3

* fix unit tests

* fix more code and tests for v3 compat

* add test for Semaphores lib

* update errors handler

* update tsconfig for sdk v3 compat

* update tsconfig for sdk v3 compat

* fix tsconfig

* fix data-migration2 code for v3 compat

* refactor

* fix tsconfig

* update CHANGELOG

* work on fixing update logic

* refactor base dynamo model update() function for compat with aws sdk v3

* add unit tests

* fix update() logic and add unit test

* fix code and unit tests

* fix unit test

* fix unit tests

* remove underscore from allowlist

* update version of simple-git

* fix stack-locking script

* fix stack locking script

* fix typo

* fix lock stack script

* fix audit

* fix credential handling for localstack

* add unit tests for services running in localstack

* fix audit issue

* remove unnecessary change

* update audit list

* update audit allowlist

* fix code for compat with v3

* update unit tests

* fix TS issue

* remove unnecessary test changes

* update TS

* change variable name

* update dynamodbstreams client

* update JSdocs

* fix async operation code for v3 compat

* publish alpha version of aws-client and update async operation ECS code

* update async operation image version

* update S3 code in aws-client package to sdk v3

* update S3 code for v3 compatibility

* update code for sdk v3 compatibility

* fix bucket map utils & unit tests

* fix unit test

* fix CMR utils package & unit tests

* fix unit tests

* fix unit tests

* fix unit tests

* fix unit tests

* update typing

* fix unit tests

* fix unit tests

* fix unit tests

* fix unit tests

* refactor S3 code

* update unit tests

* update typings and add unit tests

* fix unit tests

* fix unit tests

* fix unit tests

* fix unit tests

* remove .promise() calls

* fix unit tests

* fix TS issues

* fix TS issue

* fix ingest package TS code and unit tests

* fix TS & add unit test

* fixing TS issues and unit tests

* update S3ObjecStore to use UUID for middlewarename

* fix unit tests

* fix type

* fix TSconfig

* fix unit tests

* fix unit tests

* fix unit tests

* fix async operation code and unit tests

* update uuid deps

* fix unit test

* update code

* fix depdendency

* fix unit test

* fix integration tests

* fix code

* fix unit tests

* fix tests

* fix code

* fix code

* fix unit tests

* add unit tests

* fix unit tests

* fix unit tests

* remove commented code

* fix merge conflict error

* fix unit test and lint

* add changelog entry

* possible fix for deserializeAws_restXmlDeleteObjectsCommandError

* update lockstack

* sns receiveMessage not getting all msg

* fix changelog

* fix integration tests

* fix Cannot find module @aws-sdk/client-s3

* update timeout for db-provision

* increase WaitTimeSeconds for publish unit tests

* receive sqs messages retry

* increase sqs2sfThrottle memory

* error.code to error.name for NoSuchBucket

* update changelog

* try to fix moveGranule error

* reformat

* fix dashboard serve by cumulus api

* add dashboard endpoint unit test

* listObjectsResponse.Contents can be undefined

* increase KinesisReplay maxWaitForSFExistSecs

* pfx is buffer not array of buffers

* add more message

* update s3credentials-readme example to use client-s3

* update cumulus-test-cleanup

* lint package not found, solve Error: Can't resolve '@aws-sdk/signature-v4-crt'

Co-authored-by: jennyhliu <34660846+jennyhliu@users.noreply.github.com>
Co-authored-by: Jenny Liu <jenny.h.liu@nasa.gov>