Adds additional debug logging for distribution.
Got a test failure at 27-Jul-2021 20:05:06

TypeError: Cannot read property 'location' of undefined
     at getDistributionApiRedirect /cumulus/packages/integration-tests/api/distribution.js:276:26
     at processTicksAndRejections internal/process/task_queues.js:97:5
     at async UserContext.<anonymous>
     /cumulus/example/spec/parallel/distributionAPI/distributionApiSpec.js:104:29

So the redirect isn't coming back as a redirect.  No idea why, so I'm logging
the full payload and headers.